CREATE TABLE public.campus_news (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  title text NOT NULL,
  source text NOT NULL,
  campus text NOT NULL,
  summary text NOT NULL DEFAULT '',
  image_url text,
  published_at timestamptz NOT NULL DEFAULT now(),
  created_at timestamptz NOT NULL DEFAULT now(),
  updated_at timestamptz NOT NULL DEFAULT now()
);
GRANT SELECT ON public.campus_news TO anon, authenticated;
GRANT ALL ON public.campus_news TO service_role;
ALTER TABLE public.campus_news ENABLE ROW LEVEL SECURITY;
CREATE POLICY "Published news is public" ON public.campus_news FOR SELECT TO anon, authenticated USING (published_at <= now());
CREATE TRIGGER campus_news_updated BEFORE UPDATE ON public.campus_news FOR EACH ROW EXECUTE FUNCTION public.touch_updated_at();
DELETE FROM public.rooms WHERE author_id IS NULL AND name IN ('Hostel gist', 'Rate your lecturers', 'Confessions');