CREATE TABLE public.direct_messages (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  sender_id uuid NOT NULL REFERENCES public.profiles(id) ON DELETE CASCADE,
  recipient_id uuid NOT NULL REFERENCES public.profiles(id) ON DELETE CASCADE,
  body text NOT NULL CHECK (char_length(trim(body)) BETWEEN 1 AND 300),
  created_at timestamptz NOT NULL DEFAULT now(),
  updated_at timestamptz NOT NULL DEFAULT now(),
  CONSTRAINT different_message_users CHECK (sender_id <> recipient_id)
);
GRANT SELECT, INSERT ON public.direct_messages TO authenticated;
GRANT ALL ON public.direct_messages TO service_role;
GRANT USAGE, SELECT ON SEQUENCE public.direct_messages_id_seq TO authenticated, service_role;
ALTER TABLE public.direct_messages ENABLE ROW LEVEL SECURITY;
CREATE POLICY "Participants can read messages" ON public.direct_messages FOR SELECT TO authenticated USING (sender_id = auth.uid() OR recipient_id = auth.uid());
CREATE POLICY "Send as yourself" ON public.direct_messages FOR INSERT TO authenticated WITH CHECK (sender_id = auth.uid() AND recipient_id <> auth.uid());
CREATE INDEX direct_messages_sender_created_idx ON public.direct_messages(sender_id, created_at DESC);
CREATE INDEX direct_messages_recipient_created_idx ON public.direct_messages(recipient_id, created_at DESC);
CREATE TRIGGER direct_messages_updated BEFORE UPDATE ON public.direct_messages FOR EACH ROW EXECUTE FUNCTION public.touch_updated_at();

CREATE OR REPLACE FUNCTION public.refresh_post_engagement()
RETURNS trigger LANGUAGE plpgsql SECURITY DEFINER SET search_path = public AS $$
DECLARE affected_post bigint;
BEGIN
  affected_post := COALESCE(NEW.post_id, OLD.post_id);
  UPDATE public.posts SET
    votes = (SELECT COALESCE(sum(value), 0) FROM public.post_votes WHERE post_id = affected_post),
    comments = (SELECT count(*) FROM public.comments WHERE post_id = affected_post)
  WHERE id = affected_post;
  RETURN COALESCE(NEW, OLD);
END;
$$;
CREATE TRIGGER post_vote_count_changed AFTER INSERT OR UPDATE OR DELETE ON public.post_votes FOR EACH ROW EXECUTE FUNCTION public.refresh_post_engagement();
CREATE TRIGGER post_comment_count_changed AFTER INSERT OR UPDATE OR DELETE ON public.comments FOR EACH ROW EXECUTE FUNCTION public.refresh_post_engagement();
UPDATE public.posts p SET votes = (SELECT COALESCE(sum(value), 0) FROM public.post_votes WHERE post_id = p.id), comments = (SELECT count(*) FROM public.comments WHERE post_id = p.id) WHERE p.author_id IS NOT NULL;
DELETE FROM public.posts WHERE author_id IS NULL AND id BETWEEN 1 AND 17;